'use client'

import { useState, useEffect } from 'react'
import { FileText, ArrowRight, ShieldCheck, Scale, AlertCircle } from 'lucide-react'
import { Header } from '../../src/components/desktop/Header'
import { Footer } from '../../src/components/desktop/Footer'
import { MobileHeader } from '../../src/components/mobile/MobileHeader'
import { BottomNav } from '../../src/components/mobile/BottomNav'
import { MenuDrawer } from '../../src/components/mobile/MenuDrawer'

export default function TermsPage() {
  const [isMobile, setIsMobile] = useState(false)
  const [isMounted, setIsMounted] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 1024)
    }
    setIsMounted(true)
    checkMobile()
    window.addEventListener('resize', checkMobile)
    return () => window.removeEventListener('resize', checkMobile)
  }, [])

  if (!isMounted) return null

  const content = (
    <div className="mx-auto max-w-4xl px-4 py-6 lg:py-8">
      {/* Page Header */}
      <div className="mb-6 text-left animate-fade-in">
        <span className="text-orange text-[10px] font-extrabold uppercase tracking-widest bg-orange/10 px-2.5 py-1 rounded-full w-fit mb-3 flex items-center gap-1.5">
          <Scale className="h-3 w-3" /> Legal Agreements
        </span>
        <h1 className="font-display text-2xl lg:text-3xl font-black text-navy tracking-tight">
          Terms & Conditions
        </h1>
        <p className="text-xs font-semibold text-gray-400 mt-1">
          Last Updated: July 2026
        </p>
      </div>

      {/* Policy Card Wrapper */}
      <div className="rounded-2xl border border-gray-150/50 bg-white/90 backdrop-blur-md p-5 lg:p-6 shadow-[0_8px_32px_rgba(0,0,0,0.015)] text-left leading-relaxed text-gray-650 space-y-5 text-xs lg:text-sm">
        
        {/* Intro Alert */}
        <div className="flex gap-3 rounded-xl border border-orange/15 bg-orange/5 p-4 text-xs font-semibold text-orange-deep leading-relaxed">
          <AlertCircle className="h-5 w-5 shrink-0 text-orange" />
          <p>
            Please read these Terms & Conditions carefully. Accessing, browsing, or otherwise using the platform indicates your agreement to all the terms of use before proceeding.
          </p>
        </div>

        <div>
          <h2 className="text-sm lg:text-base font-black text-navy mb-2 flex items-center gap-2">
            <span className="w-1.5 h-3 bg-orange rounded" /> Terms of Use
          </h2>
          <p className="mb-3">
            This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className="mb-3">
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong className="text-navy">www.jenideals.com</strong> (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
          </p>
          <p>
            The Platform is owned by <strong className="text-navy">JENI&apos;S HABIBEE BAZAAR PRIVATE LIMITED</strong>, with its principal place of business at 44/1/119A, THANTHAI PERIYAR NAGAR, Aynavaram, Perambur Purasawalkam, Chennai- 600023, Tamil Nadu (hereinafter referred to as the “Platform Owner”, “we”, “us”, or “our”).
          </p>
        </div>

        <div>
          <h2 className="text-sm lg:text-base font-black text-navy mb-2 flex items-center gap-2">
            <span className="w-1.5 h-3 bg-orange rounded" /> 1. Agreement to Terms
          </h2>
          <p>
            Your use of the Platform and services and tools is governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform, including the applicable policies, which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute Your binding obligations with Platform Owner.
          </p>
        </div>

        <div>
          <h2 className="text-sm lg:text-base font-black text-navy mb-2 flex items-center gap-2">
            <span className="w-1.5 h-3 bg-orange rounded" /> 2. Platform Usage & Services
          </h2>
          <ul className="list-disc pl-5 space-y-2.5 font-medium">
            <li>To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
            <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services.</li>
            <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner.</li>
            <li>The contents of the Platform and the Services are proprietary to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.</li>
            <li>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or local laws that might apply to you.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-sm lg:text-base font-black text-navy mb-2 flex items-center gap-2">
            <span className="w-1.5 h-3 bg-orange rounded" /> 3. Governing Law & Jurisdiction
          </h2>
          <p className="mb-2">
            These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India.
          </p>
          <p>
            All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <strong className="text-navy">Tamil Nadu</strong>.
          </p>
        </div>

        <div className="pt-3 border-t border-gray-150/45 text-center lg:text-left">
          <h3 className="text-xs lg:text-sm font-black text-navy">Need further assistance?</h3>
          <p className="text-[11px] text-gray-400 mt-1">
            All concerns or communications relating to these Terms must be communicated to us using the contact info provided on this website.
          </p>
        </div>

      </div>
    </div>
  )

  return (
    <div className="flex min-h-screen flex-col bg-bg relative overflow-hidden">
      {/* Decorative background gradients */}
      <div className="absolute top-10 -left-24 w-80 h-80 bg-orange opacity-[0.02] rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-16 -right-24 w-80 h-80 bg-orange-deep opacity-[0.02] rounded-full blur-3xl pointer-events-none" />

      {isMobile ? (
        <>
          <MobileHeader onOpenMenu={() => setMenuOpen(true)} />
          <main className="flex-1 pb-20 z-10">
            {content}
          </main>
          <BottomNav />
          <MenuDrawer open={menuOpen} onClose={() => setMenuOpen(false)} />
        </>
      ) : (
        <>
          <Header />
          <main className="flex-1 z-10 bg-gradient-to-br from-orange-50/5 via-bg to-orange-50/5">
            {content}
          </main>
          <Footer />
        </>
      )}
    </div>
  )
}
